/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReplRouteImport } from './routes/repl'
import { Route as IndexRouteImport } from './routes/index'

const ReplRoute = ReplRouteImport.update({
  id: '/repl',
  path: '/repl',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/repl': typeof ReplRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/repl': typeof ReplRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/repl': typeof ReplRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/repl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/repl'
  id: '__root__' | '/' | '/repl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReplRoute: typeof ReplRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repl': {
      id: '/repl'
      path: '/repl'
      fullPath: '/repl'
      preLoaderRoute: typeof ReplRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReplRoute: ReplRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
