/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/_home'
import { Route as ProtectedHomeHomeIndexRouteImport } from './routes/_protected/_home/home/index'
import { Route as ProtectedHomeHomeSettingsRouteImport } from './routes/_protected/_home/home/settings'
import { Route as ProtectedHomeHomeCoursesRouteImport } from './routes/_protected/_home/home/courses'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHomeHomeIndexRoute = ProtectedHomeHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => ProtectedHomeRoute,
} as any)
const ProtectedHomeHomeSettingsRoute =
  ProtectedHomeHomeSettingsRouteImport.update({
    id: '/home/settings',
    path: '/home/settings',
    getParentRoute: () => ProtectedHomeRoute,
  } as any)
const ProtectedHomeHomeCoursesRoute =
  ProtectedHomeHomeCoursesRouteImport.update({
    id: '/home/courses',
    path: '/home/courses',
    getParentRoute: () => ProtectedHomeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home/courses': typeof ProtectedHomeHomeCoursesRoute
  '/home/settings': typeof ProtectedHomeHomeSettingsRoute
  '/home': typeof ProtectedHomeHomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home/courses': typeof ProtectedHomeHomeCoursesRoute
  '/home/settings': typeof ProtectedHomeHomeSettingsRoute
  '/home': typeof ProtectedHomeHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/_home': typeof ProtectedHomeRouteWithChildren
  '/_protected/_home/home/courses': typeof ProtectedHomeHomeCoursesRoute
  '/_protected/_home/home/settings': typeof ProtectedHomeHomeSettingsRoute
  '/_protected/_home/home/': typeof ProtectedHomeHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/home/courses'
    | '/home/settings'
    | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/home/courses' | '/home/settings' | '/home'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/signup'
    | '/_protected/_home'
    | '/_protected/_home/home/courses'
    | '/_protected/_home/home/settings'
    | '/_protected/_home/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_home': {
      id: '/_protected/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_home/home/': {
      id: '/_protected/_home/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeHomeIndexRouteImport
      parentRoute: typeof ProtectedHomeRoute
    }
    '/_protected/_home/home/settings': {
      id: '/_protected/_home/home/settings'
      path: '/home/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof ProtectedHomeHomeSettingsRouteImport
      parentRoute: typeof ProtectedHomeRoute
    }
    '/_protected/_home/home/courses': {
      id: '/_protected/_home/home/courses'
      path: '/home/courses'
      fullPath: '/home/courses'
      preLoaderRoute: typeof ProtectedHomeHomeCoursesRouteImport
      parentRoute: typeof ProtectedHomeRoute
    }
  }
}

interface ProtectedHomeRouteChildren {
  ProtectedHomeHomeCoursesRoute: typeof ProtectedHomeHomeCoursesRoute
  ProtectedHomeHomeSettingsRoute: typeof ProtectedHomeHomeSettingsRoute
  ProtectedHomeHomeIndexRoute: typeof ProtectedHomeHomeIndexRoute
}

const ProtectedHomeRouteChildren: ProtectedHomeRouteChildren = {
  ProtectedHomeHomeCoursesRoute: ProtectedHomeHomeCoursesRoute,
  ProtectedHomeHomeSettingsRoute: ProtectedHomeHomeSettingsRoute,
  ProtectedHomeHomeIndexRoute: ProtectedHomeHomeIndexRoute,
}

const ProtectedHomeRouteWithChildren = ProtectedHomeRoute._addFileChildren(
  ProtectedHomeRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedHomeRoute: typeof ProtectedHomeRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedHomeRoute: ProtectedHomeRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
