/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedMainRouteImport } from './routes/_protected/_main'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/_home'
import { Route as ProtectedMainMainIndexRouteImport } from './routes/_protected/_main/main/index'
import { Route as ProtectedHomeHomeIndexRouteImport } from './routes/_protected/_home/home/index'
import { Route as ProtectedMainMainStudentsRouteImport } from './routes/_protected/_main/main/students'
import { Route as ProtectedMainMainSettingsRouteImport } from './routes/_protected/_main/main/settings'
import { Route as ProtectedMainMainCoursesRouteImport } from './routes/_protected/_main/main/courses'
import { Route as ProtectedHomeHomeSettingsRouteImport } from './routes/_protected/_home/home/settings'
import { Route as ProtectedHomeHomeCoursesRouteImport } from './routes/_protected/_home/home/courses'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedMainRoute = ProtectedMainRouteImport.update({
  id: '/_main',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMainMainIndexRoute = ProtectedMainMainIndexRouteImport.update({
  id: '/main/',
  path: '/main/',
  getParentRoute: () => ProtectedMainRoute,
} as any)
const ProtectedHomeHomeIndexRoute = ProtectedHomeHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => ProtectedHomeRoute,
} as any)
const ProtectedMainMainStudentsRoute =
  ProtectedMainMainStudentsRouteImport.update({
    id: '/main/students',
    path: '/main/students',
    getParentRoute: () => ProtectedMainRoute,
  } as any)
const ProtectedMainMainSettingsRoute =
  ProtectedMainMainSettingsRouteImport.update({
    id: '/main/settings',
    path: '/main/settings',
    getParentRoute: () => ProtectedMainRoute,
  } as any)
const ProtectedMainMainCoursesRoute =
  ProtectedMainMainCoursesRouteImport.update({
    id: '/main/courses',
    path: '/main/courses',
    getParentRoute: () => ProtectedMainRoute,
  } as any)
const ProtectedHomeHomeSettingsRoute =
  ProtectedHomeHomeSettingsRouteImport.update({
    id: '/home/settings',
    path: '/home/settings',
    getParentRoute: () => ProtectedHomeRoute,
  } as any)
const ProtectedHomeHomeCoursesRoute =
  ProtectedHomeHomeCoursesRouteImport.update({
    id: '/home/courses',
    path: '/home/courses',
    getParentRoute: () => ProtectedHomeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home/courses': typeof ProtectedHomeHomeCoursesRoute
  '/home/settings': typeof ProtectedHomeHomeSettingsRoute
  '/main/courses': typeof ProtectedMainMainCoursesRoute
  '/main/settings': typeof ProtectedMainMainSettingsRoute
  '/main/students': typeof ProtectedMainMainStudentsRoute
  '/home': typeof ProtectedHomeHomeIndexRoute
  '/main': typeof ProtectedMainMainIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home/courses': typeof ProtectedHomeHomeCoursesRoute
  '/home/settings': typeof ProtectedHomeHomeSettingsRoute
  '/main/courses': typeof ProtectedMainMainCoursesRoute
  '/main/settings': typeof ProtectedMainMainSettingsRoute
  '/main/students': typeof ProtectedMainMainStudentsRoute
  '/home': typeof ProtectedHomeHomeIndexRoute
  '/main': typeof ProtectedMainMainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/_home': typeof ProtectedHomeRouteWithChildren
  '/_protected/_main': typeof ProtectedMainRouteWithChildren
  '/_protected/_home/home/courses': typeof ProtectedHomeHomeCoursesRoute
  '/_protected/_home/home/settings': typeof ProtectedHomeHomeSettingsRoute
  '/_protected/_main/main/courses': typeof ProtectedMainMainCoursesRoute
  '/_protected/_main/main/settings': typeof ProtectedMainMainSettingsRoute
  '/_protected/_main/main/students': typeof ProtectedMainMainStudentsRoute
  '/_protected/_home/home/': typeof ProtectedHomeHomeIndexRoute
  '/_protected/_main/main/': typeof ProtectedMainMainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/home/courses'
    | '/home/settings'
    | '/main/courses'
    | '/main/settings'
    | '/main/students'
    | '/home'
    | '/main'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/home/courses'
    | '/home/settings'
    | '/main/courses'
    | '/main/settings'
    | '/main/students'
    | '/home'
    | '/main'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/signup'
    | '/_protected/_home'
    | '/_protected/_main'
    | '/_protected/_home/home/courses'
    | '/_protected/_home/home/settings'
    | '/_protected/_main/main/courses'
    | '/_protected/_main/main/settings'
    | '/_protected/_main/main/students'
    | '/_protected/_home/home/'
    | '/_protected/_main/main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_main': {
      id: '/_protected/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedMainRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_home': {
      id: '/_protected/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_main/main/': {
      id: '/_protected/_main/main/'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof ProtectedMainMainIndexRouteImport
      parentRoute: typeof ProtectedMainRoute
    }
    '/_protected/_home/home/': {
      id: '/_protected/_home/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeHomeIndexRouteImport
      parentRoute: typeof ProtectedHomeRoute
    }
    '/_protected/_main/main/students': {
      id: '/_protected/_main/main/students'
      path: '/main/students'
      fullPath: '/main/students'
      preLoaderRoute: typeof ProtectedMainMainStudentsRouteImport
      parentRoute: typeof ProtectedMainRoute
    }
    '/_protected/_main/main/settings': {
      id: '/_protected/_main/main/settings'
      path: '/main/settings'
      fullPath: '/main/settings'
      preLoaderRoute: typeof ProtectedMainMainSettingsRouteImport
      parentRoute: typeof ProtectedMainRoute
    }
    '/_protected/_main/main/courses': {
      id: '/_protected/_main/main/courses'
      path: '/main/courses'
      fullPath: '/main/courses'
      preLoaderRoute: typeof ProtectedMainMainCoursesRouteImport
      parentRoute: typeof ProtectedMainRoute
    }
    '/_protected/_home/home/settings': {
      id: '/_protected/_home/home/settings'
      path: '/home/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof ProtectedHomeHomeSettingsRouteImport
      parentRoute: typeof ProtectedHomeRoute
    }
    '/_protected/_home/home/courses': {
      id: '/_protected/_home/home/courses'
      path: '/home/courses'
      fullPath: '/home/courses'
      preLoaderRoute: typeof ProtectedHomeHomeCoursesRouteImport
      parentRoute: typeof ProtectedHomeRoute
    }
  }
}

interface ProtectedHomeRouteChildren {
  ProtectedHomeHomeCoursesRoute: typeof ProtectedHomeHomeCoursesRoute
  ProtectedHomeHomeSettingsRoute: typeof ProtectedHomeHomeSettingsRoute
  ProtectedHomeHomeIndexRoute: typeof ProtectedHomeHomeIndexRoute
}

const ProtectedHomeRouteChildren: ProtectedHomeRouteChildren = {
  ProtectedHomeHomeCoursesRoute: ProtectedHomeHomeCoursesRoute,
  ProtectedHomeHomeSettingsRoute: ProtectedHomeHomeSettingsRoute,
  ProtectedHomeHomeIndexRoute: ProtectedHomeHomeIndexRoute,
}

const ProtectedHomeRouteWithChildren = ProtectedHomeRoute._addFileChildren(
  ProtectedHomeRouteChildren,
)

interface ProtectedMainRouteChildren {
  ProtectedMainMainCoursesRoute: typeof ProtectedMainMainCoursesRoute
  ProtectedMainMainSettingsRoute: typeof ProtectedMainMainSettingsRoute
  ProtectedMainMainStudentsRoute: typeof ProtectedMainMainStudentsRoute
  ProtectedMainMainIndexRoute: typeof ProtectedMainMainIndexRoute
}

const ProtectedMainRouteChildren: ProtectedMainRouteChildren = {
  ProtectedMainMainCoursesRoute: ProtectedMainMainCoursesRoute,
  ProtectedMainMainSettingsRoute: ProtectedMainMainSettingsRoute,
  ProtectedMainMainStudentsRoute: ProtectedMainMainStudentsRoute,
  ProtectedMainMainIndexRoute: ProtectedMainMainIndexRoute,
}

const ProtectedMainRouteWithChildren = ProtectedMainRoute._addFileChildren(
  ProtectedMainRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedHomeRoute: typeof ProtectedHomeRouteWithChildren
  ProtectedMainRoute: typeof ProtectedMainRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedHomeRoute: ProtectedHomeRouteWithChildren,
  ProtectedMainRoute: ProtectedMainRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
